### ISSUE TITLE
Ignore List

### ISSUE THREAD

**Issue by mufid** [mtuchowski/mdspell#2]
How do i ignore some word / whitelist word? So that for a particular word it won't be interpreted as typo.

**Comment by mtuchowski** [comment]
Currently there is no such functionality, but I was thinking about it. Do you have any particular way of providing such a list from your (user) point of view?

The solution I was thinking about would be to use a configuration file, maybe constructed like Rails i18n file. It would look like this:

```yml
en:
  - whitelist
  - this
  - words
es:
  - 
# And so on
```

Would this suite your needs?

I knew this issue would pop up sooner or later :smile:
